# Generated by Django 3.1.2 on 2020-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default='https://github.com/elena-kolomeets'),
        ),
    ]
