# Generated by Django 3.1.2 on 2020-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gif',
            field=models.ImageField(blank=True, upload_to='portfolio/gifs/'),
        ),
    ]
